#!/usr/bin/env python3

from argon2 import PasswordHasher
import argon2
# pip3 install argon2-cffi

ph = PasswordHasher().from_parameters(argon2.profiles.RFC_9106_HIGH_MEMORY)
hash = ph.hash('enter string to hash here')
print(hash)
