#!/bin/sh
if [ $# -gt 0 ] && [ -f "$HOME/wallhaven-apikey.txt" ]; then
	mkdir -p $HOME/wallpapers
	search=$(urlenc $*)
	apikey=$(cat "$HOME/wallhaven-apikey.txt")
	data=$(curl -s "https://wallhaven.cc/api/v1/search?q=$search&purity=000&apikey=$apikey")
	originals=$(echo $data|jq -r '.data[].path')
	for o in $originals
	do
		wget -q -P $HOME/wallpapers "$o"
	done
fi
