#!/bin/sh
if [ $# -gt 0 ]; then
	mkdir -p $HOME/wallpapers
	search=$(urlenc $*)
	data=$(curl -s https://wallhaven.cc/api/v1/search?q=$*)
	originals=$(echo $data|jq -r '.data[].path')
	for o in $originals
	do
		wget -q -P $HOME/wallpapers "$o"
	done
fi
