#!/usr/bin/env python3

# Performs a case-insensitive natural sort.

import sys
data = sys.stdin.read()

data = data.replace("\r\n", "\n").strip()

lst = data.split("\n")

sl = sorted(lst, key=str.casefold)

print("\n".join(sl))
