#!/bin/sh

sudo curl -s -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/bin/yt-dlp
sudo chmod a+rx /usr/bin/yt-dlp
sudo ln -sf /usr/bin/yt-dlp /usr/bin/ytdl
sudo ln -sf /usr/bin/yt-dlp /usr/bin/youtube-dl
